// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiempreSeCaeElSistema.Models;

namespace SiempreSeCaeElSistema.Migrations
{
    [DbContext(typeof(AirlineContext))]
    [Migration("20200327215412_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SiempreSeCaeElSistema.Models.Aircraft", b =>
                {
                    b.Property<int>("AcID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AcModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("AcRegisterDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AcType")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("AcID");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("SiempreSeCaeElSistema.Models.Employee", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EmpBirthdate")
                        .HasColumnType("Date");

                    b.Property<string>("EmpCardID")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EmpEmail")
                        .IsRequired()
                        .HasColumnType("varchar(320)");

                    b.Property<string>("EmpGender")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("EmpHireDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("EmpHomeAdrs")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("EmpLastName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("EmpModifiedDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("EmpPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("EmpSalary")
                        .HasColumnType("int");

                    b.Property<string>("EmpType")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("EmpID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SiempreSeCaeElSistema.Models.Flight", b =>
                {
                    b.Property<int>("FlgID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlgArrival")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FlgDeparture")
                        .HasColumnType("datetime");

                    b.Property<int>("FlgFare")
                        .HasColumnType("int");

                    b.Property<int>("RouteID")
                        .HasColumnType("int");

                    b.HasKey("FlgID");

                    b.HasIndex("AcID");

                    b.HasIndex("RouteID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("SiempreSeCaeElSistema.Models.FlightAssignedTo", b =>
                {
                    b.Property<int>("FlgEmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpID")
                        .HasColumnType("int");

                    b.Property<int>("FlgID")
                        .HasColumnType("int");

                    b.HasKey("FlgEmpID");

                    b.HasIndex("EmpID");

                    b.HasIndex("FlgID");

                    b.ToTable("FlightAssignedEmps");
                });

            modelBuilder.Entity("SiempreSeCaeElSistema.Models.Route", b =>
                {
                    b.Property<int>("RtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RtAirport")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RtDestination")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("RtID");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SiempreSeCaeElSistema.Models.Flight", b =>
                {
                    b.HasOne("SiempreSeCaeElSistema.Models.Aircraft", "aircraft")
                        .WithMany()
                        .HasForeignKey("AcID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiempreSeCaeElSistema.Models.Route", "route")
                        .WithMany()
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiempreSeCaeElSistema.Models.FlightAssignedTo", b =>
                {
                    b.HasOne("SiempreSeCaeElSistema.Models.Employee", "employee")
                        .WithMany()
                        .HasForeignKey("EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiempreSeCaeElSistema.Models.Flight", "flight")
                        .WithMany()
                        .HasForeignKey("FlgID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
